apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-05T09:35:48.5435215Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 8e384f9106d23e87a7e93fa1e526e589200b6721b6d47611aed98830f150b3c8
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  trc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-05T09:35:48.5537783Z"
    description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&quot;'
    digest: 5f2f118f7f5388af127ddf5289467821be68c2032f0a01391f36ed251429bf75
    home: trc.zaakonline.nl
    icon: trc.zaakonline.nl
    name: trc
    urls:
    - trc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-05T09:35:48.5359896Z"
