apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-06T13:21:54.6958782Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 8e384f9106d23e87a7e93fa1e526e589200b6721b6d47611aed98830f150b3c8
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  trc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-06T13:21:54.7025057Z"
    description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&quot;'
    digest: 38fda5b84b87ac2c9cdc30ef29d3ec3f7886041b2a8db980f620fc2e7d8a341d
    home: trc.zaakonline.nl
    icon: trc.zaakonline.nl
    name: trc
    urls:
    - trc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-06T13:21:54.688Z"
