apiVersion: v1
entries:
  pc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-05T09:24:08.2305038Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 8e384f9106d23e87a7e93fa1e526e589200b6721b6d47611aed98830f150b3c8
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: pc
    urls:
    - pc-0.1.0.tgz
    version: 0.1.0
  trc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-08-05T09:24:08.2357025Z"
    description: '&quot;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&quot;'
    digest: 5b2807ef1606211fd4915d4db2920136ad9996f014abba539cf31fb8b2b4f5e4
    home: trc.zaakonline.nl
    icon: trc.zaakonline.nl
    name: trc
    urls:
    - trc-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-05T09:24:08.2244675Z"
