name: Artifact Register

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master


jobs:
    register:
        runs-on: ubuntu-latest
        steps:
            - name: Check if we need to take action
              id: process
              run: |
                  if [ "${{ secrets.ARTIFACT_KEY }}" != "" ] || [ "${ARTIFACTHUB_ID}" != "false" ] || [ "${ARTIFACTHUB_ID}" == "" ]; then
                    echo "##[set-output name=success;]true"
                  else
                    echo "##[set-output name=success;]false"
                  fi
            - name: defining variables
              id: request
              if: steps.process.outputs.success == 'true'
              run: |
                  export HEADER='{"X-API-KEY": "'${{ secrets.ARTIFACT_KEY }}'"}'
                  echo "HEADER=$HEADER" >> $GITHUB_ENV
                  echo "##[set-output name=header]$HEADER"
                  if [ "${ARTIFACTHUB_USER}" != "" ]; then
                    export URL='https://artifacthub.io/api/v1/repositories/org/${ARTIFACTHUB_USER}'
                  else
                    export URL='https://artifacthub.io/api/v1/repositories/user
                  fi
                  echo "URL=$URL" >> $GITHUB_ENV
                  echo "##[set-output name=url]$URL"
                  export DATA='{"url": "'${HELM_REPOSITORY}'", "name": "'${APP_NAME}'"}'
                  echo "DATA=$DATA" >> $GITHUB_ENV
                  echo "##[set-output name=data]$DATA"
            - name: Register To Artifact Hub
              if: steps.process.outputs.success == 'true'
              uses: CamiloGarciaLaRotta/watermelon-http-client@v1
              with:
                headers: steps.request.header
                url: steps.request.url
                method: post
                data: steps.request.data
            - name: Print the response status
              run: echo ${{ steps.request.outputs.status }}
            - name: Print the response payload
              run: echo ${{ steps.request.outputs.response }}
